### ISSUE TITLE
RepeatMasker Missing for docker

### ISSUE THREAD

**Issue by xiaoaozqd** [reslp/funannotate-docker#4]
`funannotate-docker mask -i DNA_clean_sort.fa -m repeatmasker -s Viridiplantae -l ../../Database/Libraries/RMRBSeqs.embl`
#ERROR
[Oct 09 01:03 PM]: OS: Debian GNU/Linux 10, 80 cores, ~ 264 GB RAM. Python: 3.8.12
[Oct 09 01:03 PM]: Running funanotate v1.8.16
[Oct 09 01:03 PM]: Missing Dependencies: RepeatMasker.  Please install missing dependencies and re-run script

how can I used repeatmasker after docker

**Comment by reslp** [comment]
As far as I can tell this error is from the official funannotate docker container. I am not the mainter of that, so I can not help with that I am sorry. I better place for your question is the official funannotate repository. Will close the issue.
